#!/usr/bin/env bash

set -ex

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DEPS="${SCRIPT_DIR}/../resources/dependencies"

urls=(
    "https://raw.githubusercontent.com/zalando/postgres-operator/v1.11.0/manifests/postgresql.crd.yaml"
    "https://raw.githubusercontent.com/zalando/postgres-operator/v1.11.0/manifests/postgresteam.crd.yaml"
    "https://raw.githubusercontent.com/zalando/postgres-operator/v1.11.0/manifests/operatorconfiguration.crd.yaml"
)

mkdir -p "$DEPS"

for url in "${urls[@]}"; do
    curl -sL -o "$DEPS/$(basename "$url")" "$url"
done
