#!/usr/bin/env bash

set -eux

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REFS="${SCRIPT_DIR}/../resources/references"

mkdir -p "$REFS"

instance_urls=(
    "https://raw.githubusercontent.com/zalando/postgres-operator/v1.11.0/manifests/minimal-postgres-manifest.yaml"
)

for url in "${instance_urls[@]}"; do
    curl -sL -o "$REFS/$(basename "$url")" "$url"
done
